class NotFound(Exception):
    pass


class UserNotFound(Exception):
    pass


class TestNotFound(Exception):
    pass


class TestCompleted(Exception):
    pass
